// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(ToDoDBContext))]
    partial class ToDoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.ToDoCategorias", b =>
                {
                    b.Property<int>("atividade_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("atividade_Nome")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("atividade_Id");

                    b.ToTable("ToDoCategorias");
                });

            modelBuilder.Entity("WebAPI.Models.ToDoItems", b =>
                {
                    b.Property<int>("Atividade_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Atividade_DiaSemana")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("Atividade_Dia_Hora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Atividade_Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Feito")
                        .HasColumnType("bit");

                    b.HasKey("Atividade_Id");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("WebAPI.Models.ToDoLista", b =>
                {
                    b.Property<int>("lista_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("lista_CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("lista_Concluida")
                        .HasColumnType("bit");

                    b.Property<string>("lista_Nome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("lista_Id");

                    b.ToTable("ToDoLista");
                });

            modelBuilder.Entity("WebAPI.Models.ToDoUsers", b =>
                {
                    b.Property<int>("user_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("user_Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("user_senha")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("user_Id");

                    b.ToTable("ToDoUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
